# Generated by Django 4.1.4 on 2022-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.TextField()),
                ('ip_add', models.GenericIPAddressField()),
                ('serial_num', models.TextField()),
                ('model', models.TextField()),
                ('hostname', models.TextField()),
                ('os_version', models.TextField()),
                ('vendor', models.TextField()),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ('id',),
            },
        ),
    ]
