FROM alt:p10

WORKDIR /
 
# Копируем файлы проекта в контейнер.
COPY . .
# Выполняем установку зависимостей внутри контейнера.
# раскоментировать что бы собрать на маке
RUN apt-get update && apt-get -y dist-upgrade\
    && apt-get -y install vim-console libsasl2-devel\
    libldap-devel libssl-devel python3 python3-devel python3-module-browser-cookie3 gcc
# RUN pip3 install --upgrade pip setuptools wheel
RUN python3 -m ensurepip --upgrade
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt --no-cache-dir

# Выполнить запуск сервера при старте контейнера. 
# Для отображения отладочной информации добавить ключ "--log-syslog"
CMD ["python3", "networkmgmt/manage.py", "runserver", "0:8000"] 
