# Generated by Django 4.1.4 on 2024-05-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0003_alter_configurations_options_devices_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("port", models.CharField(max_length=254)),
                ("socket", models.CharField(max_length=254)),
                ("description", models.CharField(max_length=254)),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switches",
                        to="inventory.devices",
                        verbose_name="Устройство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порты коммутатора",
                "verbose_name_plural": "Порты коммутаторов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Vlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vid", models.IntegerField()),
                ("vlan_name", models.CharField(max_length=254)),
                (
                    "switch",
                    models.ForeignKey(
                        limit_choices_to={"type": "switch"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vlans",
                        to="inventory.devices",
                        verbose_name="Switch",
                    ),
                ),
            ],
            options={
                "verbose_name": "VLAN",
                "verbose_name_plural": "VLANs",
                "ordering": ("vid",),
            },
        ),
        migrations.CreateModel(
            name="SwitchPortMgmt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.CharField(blank=True, max_length=254, null=True)),
                ("socket", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("mac", models.CharField(max_length=254)),
                ("shut_port", models.BooleanField(default=False)),
                ("clear_mac", models.BooleanField(default=False)),
                ("state", models.CharField(max_length=254)),
                ("on_off", models.CharField(max_length=254)),
                ("connect", models.CharField(max_length=254)),
                (
                    "change_vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="swportmgmt.vlans",
                        verbose_name="Ch VLAN",
                    ),
                ),
                (
                    "switch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portmgmt",
                        to="swportmgmt.switchport",
                        verbose_name="Коммутатор",
                    ),
                ),
            ],
        ),
    ]
