# Generated by Django 4.1.4 on 2024-06-05 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backupcfg", "0002_days_starttime_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="starttime",
            name="date",
        ),
    ]
